# Fauna, flora e misticismo

## Introdução

Um dos principais assuntos quando paramos para conversar, eu e Ciriégola, é sobre o tema desse Capítulo, Fauna, Flora e Misticismo. Na década de 70, quando ele escreve __Sertão de Metal__^[Essa poesia se tornou música e a música de trabalho do disco gravado em 1996, em parceria com Raimuncírio Ferreira Pontes, outro poeta Pau-ferrense, que recebe o nome da própria música.], não inserida no livro, falando dos problemas sobre a fauna, flora, e nosso convívio social, que o avanço tecnológico traria para um futuro próximo, momento esse em que ainda estavam surgindo os computadores de terceira geração. E hoje como uma premonição de Nostradamus, é uma realidade. Outras obras-primas, escritas nesses últimos anos, e disponíveis na próxima seção, são __Pachamama__ e __Margaridas na Favela__, texto poéticos para reflexões profundas sobre o trato do homem para com a natureza. Grande orações, ao Deus Interior se transbordam em __Afirmações de Um Peregrino__ e em __GRASPILUXIMUTECODEFAVON__. Apreciem com carinho a próximo seção, apresentando estas poesias e muito mais.


## Poesias, prosas e textos

### Pachamama - Mãe Terra

<pre>
Pachamama, ó Mãe Terra, o que fizeram de ti
Até sinto cheiro de morte no teu suor
Pachamama, o homem pisou pesado
No solo, pra nós sagrado
Morada dos ancestrais
Seus rios apodrecidos
Animais são abatidos
Em nome do capital
O machado bronco
No tronco golpeia o vegetal
Com somenos precisão
As baleias nas marés se precipitam
E no veneno que vomitam
Tem bateria celular
Até que morra o último batráquio
Até que tombe o último vegetal
Até que sacrifiquem o último oceano	

Só assim
O homem saberá que dinheiro não se come

Pachamama, o homem branco é malvado
Pensa que tudo é comprado
Mas Mãe Terra, tem preço não
Pachamama, nos deste o berço e o sossego
A fruta que come, e o arrego
Quando a carne não presta mais
O grande Pai tá zangado
El niño manda o recado
Destrói tudo por onde vai
No horizonte uma Águia vagueia ao por do sol
Faz a sua predição:
Ó homem néscio, envolto em tecnologia
A mais dias ou a menos dias
Vai morrer só na multidão
Até que morra o último batráquio
Até que tombe o último vegetal
Até que sacrifiquem o último oceano

Só assim
O  homem saberá que dinheiro não se come
</pre>

### Passarinho De Estrada

<pre>
Quando Deus um dia
Conceder minhas asas
Para voar
Subo o oceano
No mais largo vôo
Solto o meu cantar

Na razão primeira
De todas as coisas
Também sei amar
Faço parte das cores
Da fauna e das flores
Do repente e do ar

Sou bicho alado
Passarinho de Estrada
Faço alvorada
Amo a liberdade

Gaiola pra mim não serviu
Não compreendo gente grande
Sou filho da boca do mundo
Quero num segundo
Ser mais feliz

Sou bicho alado
Passarinho de estrada
Faço alvorada
Amo a liberdade
</pre>


### Margaridas Na Favela

<pre>
Você já reparou
O mundo ao seu redor
Tá cada vez pior
Respirar no pântano
Você já questionou
A escacês maior
Tá cada vez menor
A água do cântaro

Notícias do Pará
Acabam de chegar
Tão matando a mata
É de se acreditar
Que essa esculhambação
A constituição não basta

A questão da consciência
É o que faz a diferença
Só assim renascerá de novo
As margaridas na favela

Você já percebeu
Que o tempo esgotou
Pra você que só tirou
Mas não repôs, hipócrita
Você não entendeu
E assim não reciclou
Sua atitude só ficou
Num amanhã insólito

O povo d'além mar
Já pensam em comprar
Um patrimônio nosso
A minha mão na tua mão
Pode formar multidão
Sozinho eu não posso

A questão da consciência
É o que faz a diferença
Só assim renascerá de novo
As margaridas na favela

Notícias do Pará
Acabam de chegar
Tão matando a mata...
</pre>


### Xique-Xique, Lamparina, Lagartixa E Carcará

<pre>
Se você quer saber de onde eu venho
Provenho das espécies raras do cerrado
Da lama seca empedernida do sertão
Do coração da terra do oeste do estado
Sou uma mistura de toucinho e feijão amassado
Com rapadura preta e essência de fubá
O meu cerne é carne seca sem fritura
Dessa forma eu sou mesmo essa interessante mistura
De xique-xique, lamparina, lagartixa e carcará

Adivinhe qual é a minha procedência?
A ascendência direta vem dos mandacarus
Do angico, da aroeira, da cuité e da macambira
Da lira discreta dos uirapurus
Das jacas, cajus, dos jucás, cajás, dos jacus
Das delícias pastosas de um vatapá
Meu sangue é cinzento, sem cor e sem pintura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará

Minha vinda pra cá, quer mesmo saber?
Pra nascer quase lasco de mãe a porteira
Lavaram-me com bucha e caco de telha
A centelha de vida que me deu a parteira
Foi leite de jumenta comprado na feira
Bebi muita água com casca de jucá
Para me livrar do mal e da sepultura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará

Minha cor negra parda, cinza avermelhada
Marcada ainda pelo banzo em estigma
Digna e fica como um poema nativo
Cujo crivo Panati tem o som e paradigma
Cabalístico da misteriosa letra sigma
Misture tudo isso na água de aluá
Adoçado com a raspa da rapadura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará

Sou filho dum caboclo, velho caçador
Construtor de açudes na seca nordestina
Fascina a mim até hoje a sua sabedoria
Sua energia taurina até hoje me fascina
Conhecia a pesca, a caça, asa aves de rapina
Nas armadilhas pegava paca, mocó e preá
Corró, teiú, codorniz, cangati, traíra, e mucura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará

Minha Mãe, a matriarca, luz do meu clã
De manhã, já ajeitava o fogo na panela
Um corredor de boi com o feijão macassá
Fubá e uma catemba de coco que rela
O alho roxo como tempero e despela
Ao pilão milho zarolho para o mungunzá
A mesa era um a esteira feita com ternura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique , lamparina  lagartixa e carcará

Quando a seca desolou esse lado do nordeste
Comia-se palmatória e farinha de macambira
Numa pilha de maravalha assava batata doce
Como se fosse guloseima e amarrava numa embira
O resto das raízes, pois não repor donde se tira
 Escassea a provisão, fica seco o caçuá
No roçado sem comida a vida fica uma loucura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina , lagartixa e carcará

Já dormi muitas vezes no incômodo dum jirau
O isqueiro era o improviso de um velho corrimboque
O toque da fumaça do esterco espantava muriçoca
Quando não tinha espingarda usava mesmo o bodoque
Já comi muitas frutas venenosas sem sentir nada de choque
Já fiz cabresto de jumento com couro de tamanduá
A necessidade e a precisão aqui tinham de fartura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará

O meu creme dental era a rapa nova de juá
O meu brinquedo era osso e latinha de sardinha
Minha mochila escolar era um saco plástico de bolacha
E a merenda na escola era rapadura com farinha
Eu sei que esse conforto moderno a gente inda não rinha
Mas tinha a folia de reis, as cirandas, festa do boi e vatapá
Naquilo a alegria e o delírio corria em toda largura
Dessa forma eu sou mesmo essa interessante mistura
De xiquexique, lamparina, lagartixa e carcará
</pre>


### Karma

<pre>
Karma é um termo oriental
De uma escritura sagrada
É uma completa estrada
Do começo ao terminal
É como um senhor feudal
Que avaliza seus direitos
Rege as causas e os efeitos
Rege a vida e rege a morte
Dirige o azar e a sorte
Dá direitos a quem têm direitos

Fui ontem um jovem ditoso
Era o bom da serenata
Da sociedade fui a nata
E das meninas o mimoso
Fui um corcel fogoso
Jogando terra pra trás
Hoje perdi todo cartaz
Contribui e fiz a prole
Perdi o gás do meu fole
Tudo é karma e nada mais

Meu bom Brasil, preto de angola
Bom paciente aprendiz
Tem cuidado no nariz
Pra não perder a argola
Cada vez mais se atola
Nas multinacionais
Governantes imorais
Só pensam em ganhar dinheiro
Vamos logo pro estrangeiro
Tudo é karma e nada mais

Vejo uns chorando em prantos
Porque lhe roubaram a vida
De alguma pessoa querida
Que lhes davam bons encantos
O povo não sabe quantos
Foram nossos ancestrais
Pais dos pais de nossos pais
Já se foram e já voltaram
As as tolices não mudaram
Tudo é karma e nada mais

Se hoje estou contente
No amanhã vou pensar
Tenho mais é que aproveitar
Ser um guerreiro decente
Fazer pela minha gente
Agricultores rurais
Mostrando as credenciais
De um nordestino seguro
Pois o futuro é futuro
Tudo é karma e nada mais

Está cantando um passarinho
No alto de uma palmeira
Vem uma pedra certeira
Estraçalhando o seu ninho
Os ovos cai no caminho
Por tentações infernais
Somos todos desiguais
Fiquei de fora observando
E vi de novo o passarinho cantando
Tudo é karma e nada mais

A minha voz é um grande brado
Tenho mãos que fazem  tudo
Outro nasce surdo e mudo
Manco, coxo ou aleijado
Delfim só trabalhava sentado
Outros fazem papéis marginais
Outros nos trabalhos braçais
Totalmente fora de moda
O mundo é mesmo uma bola
Tudo é karma e nada mais

Não nasci pra ter dinheiro
Sou feliz mesmo sendo assim
E quem tiver inveja de mim
Vá brigar com Deus primeiro
Não sou o último nem derradeiro
Dos Batista(s) imortais
Não tenho tristezas, jamais
Amo tudo que já fiz
E se nasci pra ser feliz
Tudo é karma e nada mais
</pre>

### Nosso Mantra: GRASPILUXIMUTECODEFAVON

<pre>
Acima  do  Grande  Espírito
Só  existe  a  infinitude
Do  Seu  inefável e incondicional  amor
Nada  pode    me   destruir  ou  derrotar
pois eu sou parte dessa Onipresente
E poderosa Energia
</pre>

### Afirmações De Um Peregrino {#poem:afirm-peregrino}

<pre>
Eu sou a fé
Sou o poder
Eu sou a beleza
Saúde eu sou
Eu sou o amor
Eu sou fortaleza

Minha morada é uma roda sagrada
Morada do Criador
Dormindo ou acordado
É forte o meu Protetor

Eu sou natureza,
A fartura em minha mesa
Eu sou alegria
E a certeza de um outro dia feliz

Minha estrada é via abençoada
Tem riqueza e esplendor
Meu pensamento é um tiro certeiro
Sou forte que nem um condor

Sou Falcão Ligeiro
Um Xamã aventureiro
Guerreiro e energia
Pachamama é minha guia e nutriz
</pre>

### Deus Em Mim

<pre>
Ó Divina, clara e infinitamente  pura Aurora
Essência viva de todos os evangelhos da terra
Minha busca de Ti definitivamente  hoje encerra
As dúvidas e especulações que guardo d’outrora

Procurei Tua presença no evangelho e na cultura
Vaguei por todos os credos  do imaginário humano
Maldito e ruim seja todo fundamentalismo insano
Que aborta Deus do interior de toda a criatura

Deus é uma circunferência infinda e onipresente
Em todo canto , pois é tudo e por vez onisciente
Está em cima, em baixo  ou em qualquer lugar

Se Ele está em mim e eu estou Nele em toda ocasião
Assim eu me recuso do cajado  de qualquer religião
Que possa separar  Ele de  mim ou de mim Ele separar
</pre>



