# Declarações

## Introdução

Um forte de Ciriégola são as suas declarações. Declarações para a sua juventude, para seus ídolos, comunidades, suas ferramentas de trabalho, para suas musas. E como ele mesmo menciona em uma de suas poesias^[Poesia na subseção \@ref(poem:oartista), intitulada __O Artista__], “O artista é aquela cara que não é casado nem solteiro, tem compromissos com o momento”. É algo tão poético e genérico, que o leitor pode levar como inspiração as suas próprias declarações. Apreciem com muita paixão.


## Poesias, prosas e textos

### Cratera De Paixão

<pre>
Vou penetrar
Por dentro do castelo
Destes teus mistérios
Da tua ilusão
Teu coração, piramidal singelo
É uma cratera negra de paixão

És uma estação em outra estação
Uma estranha no ninho
Que a canção prediz
Só terá final feliz
Em outra  encarnação

Ah, quanto tempo eu previa
Cantar uma canção pra ela
Apaixonado de amor
De verão a primavera

É uma emoção em outra emoção
Uma garrafa de vinho
Que eu tanto quis
Fazê-la aprendiz
E dona do meu coração
</pre>


### Escrava De Ouro

<pre>
Você nasceu livre qual bicho
Bendita deusa mulher
Mas o destino bandido
Lhee fez uma escrava qualquer
Ó linda escrava de ouro
Minha vida, meu tesouro
Forte parte do meu ser
Venha ver
Que a minha lira soluça
E este coração que pulsa
Também sofre com você ...
</pre>


### A Viola

<pre>
Minha viola velha e cansada
Companheira nesta vida
Hoje te vejo sofrida
Num canto qualquer bem zelada
Às vezes escuto a balada
Música triste do destino
Lembro-me, que som divino!
Das tuas cordas saiam
E as tuas notas bramiam
Um som puro e peregrino

Eu jamais disse ser dono
Da tua virtude imortal
Sou apenas serviçal
Que não te impõe abandono
És magistral no teu trono
Crepúsculo de esplendor
Irei pra onde você for
Deste-me alento na vida
Minha viola querida
Por ti hoje eu sou  cantador

Não te encontrei por acaso
Numa noite de setembro
Eu choro quando me lembro
A oferta de parnaso
Era um lindo final de ocaso
Água jorrando de um poço
Agarrei logo em teu pescoço
Lembranças que me comovem
Tu eras ainda muito mais jovem
E  eu era ainda muito mais moço

Deste-me tantos filhos na alegria
Aliás, a tua forma é feminina
Cantar foi sempre minha sina
Sonhar foi sempre um canto de poesia
Chegará certamente o nosso dia
Final, e o final é sempre assim
Que tua madeira seja o marfim
Que guardarás meus restos no abrigo
Assim, estarei definitivamente  contigo
E tu estarás eternamente em mim
</pre>


### Ação De Graças

<pre>
Que minh'alma seja grata
Ao Lennon: por  ensinar a  cantar o amor
Ao Bruce Lee: pela esperteza na luta
Ao Júlio Verne: pelas visões de futuro
Ao Ghandi: pela luta pacifica
Ao Malba Tahan: pela contextualização da matemática
Ao Davi Yanomami: pelo amor a Terra
Ao Mestre Alcides: pela sabedoria de suas ações
À Dona Josélia: por ter aberto a porta para este mundo
A Paulo Freire: por ensinar o caminho das letras
A Eliphas Levi: pelo ministério da magia antiga
À Clara Takaki Brandão: por ensinar a riqueza do nosso alimento
Ao Oscar Niemeyer: pela beleza das curvas
Ao Zamenhof: pela esperança da Neutrala Lingvo
Ao Gibran: pela beleza dos seus versos
Ao Salvador Dali: pela estética da loucura
Ao Francisco: pelo amor aos animais
Ao Castaneda: por ensinar o caminho do coração
Ao Patativa do Assaré: pela poesia da nossa terra
Ao Buda: por ensinar a grandeza da simplicidade
À Aradia: por fazer renascer a velha religião
Ao Waldo Vieira: por abrir a porta para outros  mundos
Ao Câmara Cascudo: pela grandeza do seu amor ao nosso RN
Ao Léo Artese: pela sabedoria da Águia
À Shika: por me presentear David e Aleph
Aos Bill e Bob: por estar sempre de portas abertas
Aos Panati: por ceder-nos o seu ADN
Aos Pedreiros: por ensinar a construir colunas
À Rosa e À Cruz: pelos belos ensinamentos
Aos Martinistas: por aceitar-me como seus irmãos
Ao Grande Espírito: por me ajudar a reencontrar Pachamama!
Aho!
</pre>

### Quando Você Se Vai De Mim

<pre>
Quando você se vai de  mim é  como se duas
Bandas de minha alma gemesse e se partisse
O universo todo  conspirasse e se dividisse
E minhas vãs alegrias ficassem pobres e nuas

De mim quando você se vai é como se despisse
A natureza sábia  de todos os seus atributos
E os encantos  perdessem todos os seus astutos
Modos de viver e o mito  da magia se  demitisse

Quando o tempo bafejar-me com  sua saudade
E as lembranças ameaçarem minha felicidade
Mudarei minha tática

Invadirei seus domínios sem a mínima permissão
Farei uma casa bem no  centro do seu coração
E você nunca mais permanecerá longe de mim
</pre>

### Meu Jeito De Te Amar

<pre>
Quando digo que te amo
Amo veementemente
Minha outra parte
Que por sorte
Encontrou-te num pretérito
Tão distante

Quando dizes que me amas
Amas simplesmente
Tua outra parte
Que a morte
Não conseguiu separar
Num futuro infindo

Sei que te amo
E tua alma não reclama
Mesmo sem tocar na tua pele
Nem deitar na tua cama
Meu espírito se envaidece
Se isso não procedesse
Ou se mister assim não fosse
Eu não sentia tanto  a falta do teu cheiro
Nem morria tantas vezes de saudades

Sabes também que me amas
E não reclamas, pois
A distância do meu soma
Para fazer-te mais feliz
A Nutriz de todas as coisas
Promove a saciedade de nossos desejos
E num ensejo abrupto de um acalanto
Jamais ninguém a desejou tanto
Como a solidão dos meus tristes beijos

Num futuro não muito distante
Mediante os caprichos do destino
Nossos Caminhos se cruzarão por certo
Não mais seremos como corpos despertos
Para o amor mundano da libido
Penetrarei a nudez do teu espírito proíbido
Como a loucura de uma fissão medonha
Não me importa mais que o pudor se exponha
Transformarei teu pranto em sorriso
Que não se espante os céus com o nosso espasmo
Com certeza pelo tamanho do orgasmo
Será mais um vulcão aceso no paraíso
</pre>

### Poeta Louco

<pre>
Me diz quanto queres
Pelo teu coração
Eu confesso que não sei
O que fazer , não, não
Me diz: - Vá buscar estrelas no céu!
Eu vou!
Me diz: - Vá buscar no mar
O colar de Yemanjá!
Eu vou!
Se tu queres o mundo em tuas mãos
Eu dou, eu dou
Se é pra ser como a turma do rock
Eu sou, eu sou
Só não regule
O direito sagrado
Deste poeta louco
Quero ver teu corpo frágil
Em meu corpo vivo
Sussurrar de amor
Quero ver teu sangue forte
Em meu sangue plebe
Explodir de amor
</pre>


### Jusa

<pre>
Ó Jusa
Dos olhos sem mágoas
Eu vou nessas águas
Encontrar meu céu
Ó Jusa, coração garrido
Este peito sofrido
Chora por você
Ser sonhador
Não é tão vergonhoso
Um amor escondido
Faz a gente viver
Ó Jusa, você torna a vida linda
Cheio de amor
É tudo prazer
Por isso é que vive o poeta
Seria bom se eu tivesse você!
</pre>


### Belo Arizona

<pre>
Ah, não quero pensar
Quando chegar a hora de partir daqui
Ah, o meu corpo chora sentido saudade
Não querendo ir
Meus companheiros sentirão minha falta
Povo da ribalta
Bye, bye, adeus
Bye, bye já vou
Belo Arizona de mi corazon
Mi morada por un tiempo
Bye, bye!
Bye, bye, adios!
Bye, bye já vou!
</pre>

### Nenen, A Flor Caicoense

<pre>
Nenen, minha caicoense flor
Neste meu pleito de ternura e forte gratidão
Verto o mel cardiopata da minha emoção
Para dar-te as minhas primazias de eterno amor

O calor das tuas belas formas, inebriantes
Despertou o fogo esquecido da minha liberdade
Sinto despertar o privilégio da tenra idade
Quero me perder nas tuas geografias ondulantes

Um dia chegará em que retornarei a minha cidade
Passarão muitos dias sem ver a tua linda face
Por mais que eu queira inibir o meu disfarce

Eu não posso conter a tristeza desse vil momento
Para acabar de vez com esse péssimo sofrimento
Para rever Nenen e matar minha eterna saudade
</pre>


### Horizonte

<pre>
Vamos caminhar bem juntos
Em nosso sonho de esperanças
Criando alternativas certas
Mantendo firme a confiança

O choro pode se fazer triste à noite
Mas a alegria vem pela manhã
Queremos mesmo ser livres
De toda uma filosofia vã

Segure firme as suas lágrimas
Segure firme em minha mão
Deixa a sua porta aberta
Permita-me entrar em seu coração

Sabemos que está cançado
De puxar o seu arado
Divida comigo o seu peso
Partilhe comigo o seu  fardo

É só confiar, pra frente
Olhar de novo o horizonte
Está nascendo uma luz
Que brilhará prá sempre

Segure firme as suas lágrimas
Segure firme em minha mão
Deixa a sua porta aberta
Permita-me entrar em seu coração

Já caminhamos tantas vezes
Não deixe o sonho se acabar
Chegou a sua vez agora
De sorrir e de sonhar

Diga ao seu vizinho do lado
Está  chegando um novo dia
É hora de rever as coisas novas
Novas cores e a alegria
</pre>


### A Preta Zefa

<pre>
Vovó criou Zefa junta e unida a todos nós
Zefa apesar de ter a pele bem pretinha
Nenhum preconceito a gente tinha
Mesmo quando a gente se entretia e ficava sós

Pretinha era bonita e cheia de formosura
Tinha mais força que um boi de capinadeira
Tuas tetas eram mais duras que uma pedreira
Os teus dentes reluziam a mais pura alvura

Ó Pretinha! Como eu choro e sinto de ti saudade
Fostes um presente de Afrodite à minha mocidade
Fostes a vaidade mais cara que gozei em plenitude

Entrei em teus caminhos de forma bruta e atrevida
Talvez eu tenha sido uma página branca em tua vida
Mas tu, com certeza, fostes a mais doce e bela negritude
</pre>


### Harém

<pre>
Ah! Quantas mulheres tenho amado tanto
Ah! Quanto pranto derramei por todas elas.
Em cada canto do meu canto
E em cada verso do meu fado
Tenho-as guardadas no manto
De tantos poemas eternos
</pre>


### Brasil Samba 10000

<pre>
Samba que me grita apaixonado
Descansa no silêncio do murmúrio
Como toureiro que explode no delírio
Como o colírio se expande dos seus olhos
Porque choram de vontade
Voar é o seu sonho peregrino
É nacional o seu sangue prateado
É namorado
Da “Pantera Cor de Seda”
Um cabaré em palco cinza
Que reclama sua falta com saudade
Dos aplausos nas alcovas se consagra
Quantas bocas se abriram em sorrisos
E se você se extinguir no modernismo
Eu também morrerei
Brasil samba 10.000
</pre>


### Dora

<pre>
Ó Dora
Dos olhos sem mágoas
Eu vou nessas águas
Encontrar meu céu
Ó Dora, coração garrido
Este peito sofrido
Chora por você
Ser sonhador
Não é tão vergonhoso
Um amor escondido
Faz a gente viver
Ó Dora, você torna a vida linda
Cheio de amor
É tudo prazer
Por isso é que vive o poeta
Seria bom se eu tivesse você!
</pre>

### Uma Canção Para Uma Mulher De 62

<pre>
Ah! Como eu lembro de você bela mulher de 62, para alguns você é apenas 
mais uma no rebanho humano cumprindo os desígnios do seu tempo e 
colhendo os frutos das suas escolhas, mas eu ainda continuo vendo por entre 
as suas rugas e cicatrizes a beleza da sua alma e o cheiro doce do seu 
perfume natural de serra de encanto. Eu conheço o seu destino e você conhece
o meu, pois somos frutos da mesma senzala e somos índios da mesma aldeia,
trabalhamos na mesma seara. Ah! mulher de 62, você não sabe, mas eu te 
encantei em um dos versos de minhas canções e guardei a memória os doces
acordes nas crônicas do meu coração, sim guardei no coração, pois é lá o 
lugar apropriado para guardar as coisas sagradas de sentimentos puros sem
promiscuidade e sem a possessão do egoísmo humano, sim, no CORAÇÃO: a Terra
onde todos são LIVRES para sonhar o que quiser, inclusive AMAR os outros de
forma INCONDICIONAL.
</pre>


### O Último Voo Da Velha Águia Pau-ferrense

<pre>
A Águia sempre foi considerada um animal Sagrado em todas as culturas deste
planeta, dizem que é o único ser vivo capaz de encarar o Sol de frente e dos
vertebrados o único que passa por uma metamorfose em uma única existência como
a lagarta, entre tantas qualidades divinas, a Águia é um animal de grande
porte, de costume solitário nobre e caráter singular. A nossa Águia
Pau-ferrense fez agora o teu último voo e passa a trilhar o Caminho Azul do
Espírito, sai de um mundo de provas e expiações para Esferas de padrão
vibratório elevado e com certeza se apresentará ao Grande Espírito sem se
envergonhar da missão que cumpriu, pois assim foi o teu ministério terapêutico,
social, político e tantos outros adjetivos que não cabem nesse espaço grosseiro
e impróprio para tal fim. Não vamos sentir muitas saudades de Ti, temos
guardado em nosso coração a Tua Imortal Lembrança compassiva de Alma Boa e
justa, seres da Tua espécie NÃO MORREM ZÉ, apenas mudam de estado como As
BORBOLETAS e as ÁGUIAS. Boa viagem!!!!
</pre>
