# Família

## Introdução

Eu quando menino, ainda não havia nascido meu irmão caçula, Aléfe Batista, adorava esperar meu pai chegar para assistirmos desenho juntos. Adorávamos o Pica-Pau, dentre outros. Porém, à demora pela sua chegada do trabalho, era um tempo sem fim. Ao ponto, de eu ter que esperá-lo na esquina da Rua Hipólito Cassiano com a Rua 4 de Setembro, em Pau dos Ferros/RN. Esta última tem uma ladeira cuja subida vai ao encontro da Escola Estadual Tarcício Maia. Era lá o trabalho do meu pai, de modo que quando eu avistava, corria o máximo que podia. Daí surge a poesia __Pimpolho__, que logo em seguida, se torna música, e quando a canto, sempre volto ao mesmo lugar, a inocência de um sonhador.

Temos também muitas outras emoções, como __Colibri__, dedicada ao meu irmão Álefe Batista, __Uma Ala Na Luna__ dedicada a Allanna Lopes, e ao nosso aconchego familiar, __A Casa do Meu Pai__, que se refere ao meu avó Alcides Batista. Por fim, __Manhã, Tarde e Noite__ é o retorno para a sua casa, após as viagens, ao encontro de nossa Matriarca, Chica Batista. Sintam um pouco de nós, e leve apenas o que for bom!




## Poesias, prosas e textos

### A Casa Do Meu Pai

<pre>
Eu sempre vou
Para casa do meu pai!
Por lá  ninguém jamais  vai
Ferir-me   ou magoar
Aqui por fora
Quando a coisa está preta
Eu pego minha maleta
E vou pra casa do pai
Eu sou filho único
E apesar da dependência
Minha mãe  tem paciência
Cura toda minha dor
Minha casa tem poder e alegria
Amor e sabedoria
Tem calor, sossego e paz

Eu sempre vou
Para casa do meu pai!
Quando a cabeça não sai
De pensamentos ruins
Esse tesouro que mora  dentro da gente
Buscá-lo fora é somente
Embriagar-se de ilusão

Eu sempre vou
Para casa do meu pai!
Quando a dúvida me atrai
Ou me sinto tão sozinho
Depois disso sinto um bem estar profundo
E se eu não sou dono do mundo
Mas o dono é meu pai
Da minha casa
Posso ir pra qualquer canto
Não me assusto  e não espanto
Em tudo que posso olhar
Se este lugar que fica dentro da gente
Fosse mentira somente
Precisava-se inventar

Eu sempre vou
Para casa do meu pai!
O dia é sempre manhã
Onde o pai também é mãe
Onde a mãe também é pai
Este hibridismo natural e tão ditoso
Faz–me  forte e poderoso
Mexer comigo, quem vai?
Todo dia eu vou
Para casa do meu pai!
</pre>

### Pimpolho

<pre>
É tarde
Tocam os sinos na matriz
São seis horas
Eu preciso descançar
Quando eu vejo
Na ladeira meu pimpolho
Chamando seu papai
Para o jantar
Pra que lamentar
As ilusões que já passei
Melhor será  agradecer a Deus
Ainda sou feliz
Ave Maria! Cheia de graça
Saúde pra Chica meu bem
Não deixe faltar o pão de cada dia
Protege meus filhos também
</pre>

### Uma Ala Na Luna

<pre>
Eu dei e vi de você
Minha melhor oração
Chorei quando vi em você
A semente no chão

Ao leu foi dado aprender
Que o amor tem poder
Que o amor tem razão

Uma ala na luna traz vida ao meu coração
Amanhã será farta e feliz minha geração
Parei pra pensar e a deus agradeci e entendi
Que a felicidade nesta minha idade
De outubro já vinha em minha direção

A lei fez feliz minha fé
Ache caro e ruim quem quizer
Disso eu não abro mão

Do seu lado quem vem vai lhe ver
Redonda  e num feliz  amanhecer
Seu rebento não surgirá em vão

Uma ala na luna faz viva minha emoção
Seus pequenos: minha prole \emph{ben} dita
</pre>

### Manhã, Tarde E Noite

<pre>
De manhã  quando o vento sopra
Sinto a brisa leve
Que vem do mar
Sinto uma saudade louca
E uma vontade lúcida
De voltar
De voltar pra casa
Vai caminheiro na frente
Diga a Chiquinha
Que eu vou chegar
Deixe a rede na varanda
E pinga boa pra gente tomar
Linda morena
Teta de cuscuz
O que me seduz
E o teu negro olhar
Chuva maneira que vem do nascente
Seja complacente
Deixe o chão molhar

A tarde  quando o sol descansa
A garça retorna
Pra se agasalhar
No horizonte desponta
Um fiasco de esperança
Da volta...
Da volta pra casa
Oh Benjamim, maestro do bom
Chame seu Benom
Que a banda vai tocar...
Dona Altina chame Bastião
Acenda o fogão
Pro feijão cozinhar

A noite  quando os sinos dobram
Cobram  minha presença
No chão do meu lar
Meu coração palpita
Se alegra e se agita
Pra voltar...
Pra voltar pra casa
Oh seu Matias venha bem ligeiro
Prepare o terreiro
A gente vai dançar
</pre>

### Para Dona FLÔ

<pre>
Anos 80, nenhum motivo faria me esquecer dessa década, no comecinho
de 80 eu vinha chegando de São Paulo, a cidade dos sonhos de muitos
jovens que como eu ouvia o 14 Bis e a Banda Eva, foi mesmo por essa
época que me encontrei pela primeira vez com dona Flô, minha FLÔ do
Apodi/RN. Nessa época eu tinha um fusca laranja, quer dizer, era de seu 
Alcides meu pai, mas eu mentia para todas elas e tinha muitos sonhos e
muitas estórias na ideia. Foi também nessa época maravilhosa que eu
encontrei aquela galeguinha acanhada vinda do Sítio Bico-Torto às
margens da Lagoa Apodi: minha FLÔ (Francisca Leite de Oliveira –
Chica), ela tinha um pouco de nada e eu nem de nada tinha um pouco,
mas eu tinha o mundo pela minha frente porque eu tinha LIBERDADE como
criatura pensante. Naquela época existia o Bar da Aviação o qual 
ficava no comecinho do Conjunto Princesinha (Pau dos Ferros/RN), ali
era também o começo do velho campo de pouso, naquele pátio grande 
vimos muitas vezes a madrugada chegar, só eu, Chica e o velho fusca. 
Foi o melhor tempo da minha vida, muitas canções foram escritas 
naqueles tempos, todo meu imaginário era pura criatividade, eu 
respirava música e dormia nos braços da poesia, mas tinha um detalhe 
interessante: eu procedia daquela forma simplesmente porque gostava de
viver daquela maneira, meu corpo físico exibia o esplendor dos meus 
vinte e poucos anos e os hormônios vazavam por todos os poros. Foi 
nessa época em que encontrei minha FLÔ, Chica de Bento de Tito lá do 
SBT (Sítio Bico-Torto), como muita gente conhecia minha rotina sabia 
que minha vida era uma festa diuturna e enchiam a cabeça de Chica de 
bobagens, mas eu sempre falava para minha galega: que maior do que meu
amor por ela só a coroa do Criador e a vontade de andar naquele fusca 
velho, então eu via nos olhos inocentes da minha FLÔ que ela confiava
no meu destino. E assim junto a minha odisseia franciscana eu comecei
e terminei minha primeira graduação. Nesse interim eu já tinha casado
com Chica nos três cartórios e já tínhamos perdidos três crianças,
dois desses meninos voltaram depois com muito vigor e graça do Grande
Espírito: Ben e Álefe. Esse ano de 2015, fez 31 anos que nós
caminhamos juntos por essa estrada divertida a qual tem um significado
muito maior do que um matrimônio igrejista e civilista, eu sou minha
esposa, minha esposa é meu outro lado, nós somos um clã unido como uma
alcateia de lobos, nos amamos mutuamente sem precisar usar o verbo
porque o coração sempre se antecipa na trivialidade das nossas ações.
Hoje minha FLÔ completa mais um ciclo de vida, posso perceber a
covardia do tempo ao dobrar-lhe a tez e o começo de um colorido
degradê invadir seus cabelos, ainda assim sinto a fragrância e o
frescor do seu carinho como a 30 anos atrás, seus cuidados pelos seus
três homens continuam impecável como antes. O afã da sua labuta
continua religiosamente como antes, de vez em quando ouço dos vizinhos
da comunidade o quanto dona FLÔ é grande e poderosa, mas com toda essa
consciência e certeza no meu convívio domiciliar ainda não tive a
coragem e o atrevimento suficiente para dizer a essa senhora o que
sinto, porque não confio na articulação das palavras, minha
companheira é muito mais do que a mãe dos meus filhos, só quem
caminhou 30 anos ao seu lado sabe o tamanho da preciosidade que o meu
destino reservou, eu não sei o tamanho desse preço e sou covarde o
suficiente para dizer que não tenho capacidade de arcar com essa
vultosa quantia, mas tenho dito entremeando minhas canções, aqui e
ali, minha mais profunda gratidão em forma de otimismo e alegria nesse
caminhar infindo de idas e vindas. Minha querida Chica, minhas
sinceras congratulações na passagem desse seu dia, no seu presente
está contido minha vontade de sempre acertar mais ainda nessa nossa
caminhada que nos levará para o nosso verdadeiro lar. Que o Grande
Espírito a abençoe abundantemente e perpetue a nossa semente!
</pre>
<div align="right" >
_Texto escrito em 06/11/2015 (Aniversário de Chica Batista), nas redes sociais de [Ciriégola](https://www.facebook.com/josealcigeriobatista.alcigerio)_
</div>
