# Adjetivações

## Introdução

Qualificar situações, coisas, pessoas, dentre outras, é marca de Ciriégola. A ideia em __O Artista__ mostra a plasticidade e a onipresença que o Poeta sempre deve estar para descrever a profissão. Ao passo que sua inquietação se apresenta em o __Destino__. Mas qualificar, transcendendo a matéria, bem como adjetivar a sua __Alma Gêmea__, mostra a grandiosidade de Ciriégola. Aprecie com moderação estas dentre outras poesias, ou mergulhe em suas sensações com a leitura.

## Poesias, prosas e textos

### O Artista {#poem:oartista}

<pre>
O artista é aquele cara que...
Nem ama nem odeia, se harmoniza
Não come e nem consome, comunga
Não é bom nem mau, é justo
Não é bonito nem feio, é interessante
Não é inteligente nem sábio, é desperto
Não é casado nem solteiro, tem compromissos com o momento
</pre>

### Destino

<pre>
Era uma estrada longa
Um rapaz jovem e bandido
Um violão afinado
Um coração novo e lutrido
Seu destino e sua meta
Era andar e ser poeta
Sem bandeira e sem partido

Rapaz aquele, destemido
Pensava ter nascido pra andar
Mas como a sorte é mesquinha
Só bota em nós pra lascar
Ele encontrou um dia
Uma moça chamada Maria
Tudo passou a mudar

Mestre EROS veio deixar
Seu coração inflamado
Que também não conhecia
O preço do seu legado
O jovem então parou
E sua estrada tomou
Um rumo inesperado

O violão ficou parado
A sua estrada cadente
O moço envelheceu
Ficou todo diferente
Tudo ficou ruim
Ele conheceu Caim
O diabo em forma de gente

Passou a  viver somente
Andando de bar em bar
Com ciúmes e com paixão
Vendo fantasma no ar
A sua Maria sumiu
Encontrou outro e partiu
Ele, do sul, veio pra cá

E pra história encurtar
Hoje vive escondido
Numa casinha de taipa
O violão esquecido
Um moço velho babando
Até nas calças mijando
Um coração velho e fudido
</pre>

### Alma gêmea

<pre>
A alma gêmea é aquela alma que nos transmite a suprema alvíssaras
Toda vez que a vemos o coração estremece como um cavalo bravio
Seu sangue ruboriza os malares faciais denunciando nossa condição
Instantânea de juvenilidade como se explodisse toda carga da libido
Toda vez que a vemos é como se despertasse um vulcão enfurecido
Roendo e corroendo de dentro para fora todo prenúncio de tristeza
A alma saltita à procura de qualquer palavra que lhe dê um verso
Uma palavra qualquer se transmuta em uma ode de Cervantes
Esta alma pode não ser eterna, mas imortaliza sempre o momento
Santifica todas as coisas por mais medíocres ou promíscuas que sejam
A alma gêmea é o cadinho do alquimista ansioso pelo o ouro da vida
Manifestada em lândrias e enfeitada de relevos na anatomia do colo
A criatura nos transporta para esferas jamais imaginadas por Dante
Ah, como é magnífico o nosso primeiro encontro com a alma gêmea
Voltamos a infância dos nossos dias mais caros de primaveras
Introspectamos e somatizamos por osmose todas as coisas visíveis
Alternando do mal para o bem, do mau para o bom constantemente
Parece que alma gêmea cheira a todos os requintes de paixão diáfana
Ou seria a nossa contraparte atraída pela mesma parte de Narciso?
Raramente as pessoas encontram essa sua parcela de similitudes e
Raramente a temos por muito tempo nas lidas das existências terrenas
Os poetas simulam no continuum vários encontros com almas gêmeas
Chamam de musas cujas fêmeas funções são o esteio de suas obras
O calor metafísico nas noites frias de solidão austera, inexorável e
Saudosismo iminente que avassala e condena a alma a amar sempre
</pre>

### O Amor

<pre>
O amor é tão interessante
Que se eu amar você
Amo a mim mesmo
Se eu me amar
Amo a todos vocês
Contudo, se o meu amor do qual professo
Tiver  origem na química dos  hormônios
Ele se torna  tão egoísta
Que se transforma com estranha facilidade
No ódio que conflita
Se transforma em medo
E destrói como um vendaval desgovernado
E cheio de dúvidas
Por isso já ouvimos alguém dizer
Certa vez que matou por amor
Nós, os humanos, somos tão estúpidos!!!!!
</pre>

### Efeméride (13 De Setembro)

<pre>
Obrigado a todo mundo
Fica minha gratidão
Pra mim, isso é todo dia
E todo dia em oração
Agradeço a Deidade
Pela minha LIBERDADE
Luz, Saúde e Guarnição

Foi um ano muito bom
Foi um ano bom demais
De novo fiz minha parte
O resultado me apraz
A Voz Oculta me diz
Que minh'alma está feliz
E minha casa está em Paz
</pre>


