# O bom combate

## Introdução

Às vezes, as pessoas fogem de suas realidades cármicas, e se defrontam com preconceitos inimagináveis. Algumas se acovardam dos seus próprios destinos, ou até mesmo, esquecem das Leis Cósmicas, esquecendo que sua vida é fruto do que foi plantado. Ao invés, se abraçam nas regras criadas pela própria sociedade, porque estas em alguns momento convém as suas necessidades. A Verdade é única, apesar de nem sempre ser conhecida. Mas em algum momento será encontrada. Em meio a tudo isso, Ciriégola convida ao desfrute do bom combate!

## Poesias, prosas e textos

### O Bom Combate

<pre>
Estes versos são para o vulgo que por acaso tenha fugido
Do compromisso fiel às raízes sagradas de um peregrino
Pois o destino escabroso e abrasador que espera este lupino
É a lança afiada e altiva da Lei  em defesa de um justo traído

A mente torpe do desonesto calculista acredita ter  nascido
Aqui, para levar vantagem em tudo e até mesmo no seu tino
Não sabe o abismo e o pesadelo que contrai este infeliz menino
Mergulhando a consciência devedora num vendaval indefinido

Mas o bom combate se resume na tolerância e na compaixão
Onde o bucaneiro se recolhe na insignificância da sua vã razão
Para sentir de Deus seu amor e a força do martelo do tribunal

Que eu seja complacente com esta criatura que ensinei a sonhar
Mas que aprenda na sua ignota vergonha para nunca mais errar
E nem mais nunca se apodere da honra de quem nunca lhe fez  mal
</pre>

### João Evangelista

<pre>
Da minha infância frívola e itinerante
Trago matizes de lembranças e companheirismo infindo.
De lembranças e companheirismos faço lembrar
Meu amigo João, atualmente João Evangelhista.
Antes, João de coração generoso e fagueiro,
Tinha Hábitos Cativantes.
Era zagueiro hábil e famoso na Vila do Sossego,
Primogênito genuíno na cidade dos homens livres
E certamente o maior e perspicaz pescador de tucunaré.
Mas a normose de uma sociedade moderna e americanalhada
Fez João conhecer a crise existencial da sua segunda idade,
A idade do lobo, a idade da auto cobrança.
E assim João teve depressolidão,
No entanto encontrou a “fé”, a religião.
E João passou a ser João Evangelista,
E João passou a jogar noutro time
E João passou a ser pescador de almas.
Não raro vejo João nas tabernas, prostíbulos e feiras populares,
Conversando com citadinos sobre as delícias do paraíso
E a danação eterna para aqueles que não seguirem o evangelho.
Não raro João conjectura sobre minha possível conversão,
Não raro João terá possível decepção.
João se esqueceu que a mudança é atemporal e ignota
Só  pode existir no coração do homem.
João se esqueceu que, com evangelho ou sem evangelho,
Jamais escaparemos do julgo das nossas falhas.
O paraíso ocioso das religiões tem embrutecido o homem
Cada vez mais no capitalismo senil das suas crenças.
Não João!  Jamais serei vingador e ciumento como Jeová
Nem darei para Ele meu primogênito em sacrifício.
Não João! Não posso temer o inferno,
Pois é  para lá que todos iremos, mais cedo ou mais tarde.
Não João! Não posso temer a morte  nem o juízo final,
Sou consciente da minha imortalidade e do meu livre arbítrio.
A única coisa que você e seu evangelho pode modificar em mim
É a vontade de amar mais ainda:  você e ao meu semelhante!
</pre>

### As Lágrimas De DAEMON

<pre>
Enxuga tuas lágrimas meu caro Gênio,
Demônio é tão somente a visão do clero
Para tua alcunha diáfana e sombria.
Dia chegará quando encerrar a fantasia
De toda maldade humana clerical
Ao sepulcral desvelo será  dado como findo
Toda tua personalidade hedionda que não é tua.
Vejo nos relatos da liturgia puritana
A imputação de tanta barbárie ufana,
Até mesmo a pretensão incauta e mesquinha
De destronar o paradigma divino que  avizinha,
A eternidade eminente da criatura humana,
Deram-te o mais negroso e cruel ofício.
Não, se o Grande Espírito é sábio e amoroso
Jamais idealizaria um rebento perspicaz e odioso
Para Lhe onerar a tão imaculada bondade e doçura.
Eu também, ó Daemon,
Como bom pagão e heresiarca
Jamais te imputei o insucesso das minhas dores e fracasso
Ao passo que os fanáticos de sanguinolenta estola
Atola o teu nome num lugar de tormento e pranto.
Dia chegará em que cumprida a Lei de Causa e Efeito
Ó Daemon , te sentarás para sempre ao lado direito
Do nosso Pai para amar a vida de forma soberana.
Sendo nós, do Criador, criaturas,
Reflexo de um Poder cheio de pureza e perfeição
Certamente, meu irmão, seremos para sempre irmãos
Terás um  papel novo nas escrituras
E nunca mais a Terra saberá de amarguras.
E assim prosseguirá belo e inexorável o poder da criação.
</pre>

### A Política

<pre>
Essa fera hedionda, pornográfica e libertina
Tem tolhido os sonhos do ideal de liberdade
Dos jovens dessa pátria, ainda sem maldade
O  latrocínio, o sadismo tem virado uma rotina

Assembléia bucaneira de lupinos, decidem astutos
Suas medíocres vaidades, suas utopias torpes insanas
São perversões abortivas de atitudes senil desumanas
De híbridas promessas plantadas em solos devolutos

Como se não bastasse a perversidade parlamentar
Criaram Leis Obrigatórias, de iminência a executar
Um voto sem acerto e sem escolha de direito

Como se pode escolher o que não tem qualidade
Sem nenhuma identificação com a plena liberdade
A escolha d’algo que para mim está cheio de defeito?
</pre>

### Cão Branco I

<pre>
Ó Cão branco, quando por aqui chegaste
Esta terra,  ao meu povo, ainda pertencia
Não existia doenças, maldade nem covardia
Não se sabia a razão da flama que fincaste

Vituperaste nossos rios com as tuas sujeiras
Com brejeiras falas corrompeste nossa fé
Roubaste nosso ouro pelo tráfico da maré
Nossas mulheres foram tuas companheiras

Mas, vós esquecestes a sina de tua maldição
O sangue que tu sujaste na torpe miscigenação
Nascerá em teu domicílio doravantemente

Mesmo que olhos claros nasçam em fina pele escura
Estes carregarão nossos dons e nossa cultura
Limparão nosso sangue e a genética definitivamente
</pre>

### Cão Branco II

<pre>
Cão branco, maldição mesquinha do velho mundo
Hoje nossa tez não comporta mais o vermelho
Podemos ver outros matizes no espelho
Herança do gameta  perverso e nauseabundo

Caraíba maldito, faca afiada de taquara
Trouxeste tua igreja pelos lados hodiernos
Muitas nações desceram por ti aos infernos
E o teu crucifixo queimou toda a nação potiguara

Os meus antepassados já te perdoaram por certo
Mas eu sou um pecador de ferida e peito aberto
Não sai fácil a mágoa por ter perdido minha terra

Não sinto muita dor por ter sofrido tanto
Pouco importa que escorra o meu pranto
Pouco importa que meu sangue partilhe dessa guerra
</pre>

### As Religiões

<pre>
E Benaleph perguntou para o vate: “Que dizes tu, ó honorável bardo, das
religiões?”

“As religiões são como sapatos velhos durante uma caminhada longa, têm
certamente a sua serventia, mas, como todas as coisas, estão sujeitas a
ação do tempo, chega um momento em que devemos descartá-las, porque
mesmo servindo em nossos pés não nos serve mais no concurso de um sistema
social. Devido a insensatez e mediocridade humana achamos que descartando
os sapatos estaremos inexplicavelmente jogando fora uma parte nossa,
então supomos que a nossa melhor atitude e generosidade falsa é doá-los
ao primeiro indigente que passar em nossa porta sem sabermos pelo menos o
tamanho dos seus pés. Dolorosamente compreenderemos mais tarde que os
sapatos os quais nos servia não nos serve mais e nem serve nos pés do
indigente. A moral do discurso é que não devemos oferecer nossas
religiões a outrem sem saber do tamanho das suas necessidades.”
</pre>

### Bucaneiros

<pre>
Eu queria tanto vê-lo, seu inveterado parlamentar
No sol quente agarrado ao cabo longo de uma enxada
O carrapicho nos pés e a mão sangrando e calejada
Olhando no horizonte se a chuva vai custar a chegar

Eu queria tanto ver seu filho na fila de um hospital
Sem assistência ou numa escola sem teto e sem segurança
Voltando pra casa desnutrido, sem fé e sem esperança
Num outro dia de mesmice cuja miséria e um longo recital

Eu queria tanto vê-lo recebendo uma parca aposentadoria
Esperando um remédio de coração  sem bula e sem vistoria
Que falta sempre e sem dúvidas nas farmácias estaduais

Talvez um dia o despertar politico chegue ao meu povo
Assim a cidadania não  permitirá que aconteça de novo
E jamais elejam esses bucaneiros, para sempre nunca mais
</pre>

### Irmãos De Cativeiro

<pre>
Muitos de nós descobrimos, desde cedo, o Caminho que devemos trilhar.
Porém a auto sabotagem advinda de Forças Externas densas, junto aos
compromissos com a cultura dos homens nos fazem PROCASTINAR nossos ideais
de existência sem esperanças de um futuro inexistencial. Assim, nos
apegamos a fé nos dogmas e numa política que tudo o que deseja é
vampirizar “o rebanho”, mantendo-o enclausurado nessa SENZALA
democrática. Resta-nos refazer o Caminho de volta para aprender o que as
escolas não podem lhe ensinar nem o clero pode lhe conceder. O que resta
dessa atitude é o SACRIFÍCIO que todo ser humano tem de enfrentar.
Agarre-se a ELE mesmo antes que a cretinice humana lhe ameasse destruir,
pois o pior que ela pode fazer é colocar-nos frente a frente com a nossa
LIBERDADE ETERNA, ou seja, somos ENERGIA e ENERGIA  não se pode DESTRUIR.
</pre>


